export type CREATE_GAME_ERR_STATUS = "CANNOT_LEAVE" | "INTERNAL_ERROR";
export type CREATE_GAME_STATUS = CREATE_GAME_ERR_STATUS | "SWITCH" | "SUCCESS";

export type JOIN_ERR_STATUS = "ALREADY_JOINED" | "CANNOT_JOIN";
export type JOIN_STATUS = CREATE_GAME_STATUS | JOIN_ERR_STATUS | "SUCCESS";

export type ERR_STATUS = CREATE_GAME_ERR_STATUS | JOIN_ERR_STATUS;
